### ISSUE TITLE
TypeError: Cannot read property 'digital' of undefined

### ISSUE THREAD

**Issue by peterschmiz** [tessel/gps-a2235h#29]
Hi,

After installing the npm package and trying to run the example code on my Tessel2 I got the following error:

`TypeError: Cannot read property 'digital' of undefined
    at new e (/tmp/remote-script/node_modules/gps-a2235h/lib/tessel_2/driver.js:
1:301)
    at Object.e [as use] (/tmp/remote-script/node_modules/gps-a2235h/index.js:1:
90)
    at Object.<anonymous> (/tmp/remote-script/gps.js:1:127)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3`

My Tessel 2's firmware is the latest. Could you please help me or check if you can reproduce the issue on Tessel2?

**Comment by johnnyman727** [comment]
@peterschmiz it looks like the example in the README and the first run experience are out of date. I updated the example in the README and the examples folder of this repo so it should work. Go ahead and give them a spin (make sure the GPS module is plugged into port A).

**Comment by peterschmiz** [comment]
Thank you!
